
server:
  port: 9998 #服务注册中心端口号
eureka:
  instance:
    hostname: localhost #服务注册中心IP地址
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone:  http://wangzhzh:wzz123@localhost:9999/eureka/


spring:
  application:
    name: eureka-server
  # 安全认证的配置
  security:
    #  basic:
    #  enabled: true
    user:
      name: wangzhzh  # 用户名
      password: wzz123   # 用户密码